---
namespace: 'r_pufky'
name: 'srv'
version: '13.1.1'
readme: 'README.md'
authors:
  - 'Robert Pufky <rpufky@gmail.com> (https://github.com/r-pufky)'
description: |
  Serve. Complete infrastructure management. Provide bare-metal,
  virtualization, container, OS, and service management.
license_file: 'LICENSE'
tags:
  - 'linux'
  - 'proxmox'
  - 'pve'
  - 'container'
  - 'lxd'
  - 'infrastructure'
  - 'service'
  - 'tools'
  - 'networking'
dependencies:
  'r_pufky.lib': '>=13.0.3,<14.0.0'
  'r_pufky.data': '>=3.0.2'
  'r_pufky.deb': '>=13.0.4,<14.0.0'
  'ansible.posix': '=1.6.2'
  'community.general': '=10.6.0'
  'community.mysql': '=3.13.0'
  'community.postgresql': '=3.14.0'

repository: 'https://github.com/r-pufky/ansible_collection_srv'
documentation: 'https://github.com/r-pufky/ansible_colection_srv/docs/README.md'
homepage: 'https://github.com/r-pufky/ansible_collection_srv'
issues: 'https://github.com/r-pufky/ansible_collection_srv/issues'

build_ignore:
  - '*molecule/*'  # Do not include molecule testing in release.
  - 'ansible.env'  # Development ansible environment.
  - '.ansible'  # Ansible collection cache for role testing.
  - '.vscode'  # VSCodium settings.
  - 'TODO.md'  # Development staging todo messages.
  - 'COMMIT.md'  # Development staging commit messages.
  - 'roles/dnsrobocert'  # TODO(collection): remove when migration completed.
  - 'roles/gpu'  # TODO(collection): remove when migration completed.
  - 'roles/fika'  # TODO(collection): remove when migration completed.
  - 'docs/*'  # Development docs are a separate repo and not end user.
