---
###############################################################################
# Firmware Role Options
###############################################################################

# Last time debian options were validated against a default configuration.
gpu_role_validate_date: '2025-02-18'
gpu_role_validate_release: 'bookworm'

###############################################################################
# APT Packages
###############################################################################

gpu_role_packages: []

# Debian APT sources to use if package install fails.
gpu_role_apt_debian_all:
  - name: 'debian'
    types:
      - 'deb'
      - 'deb-src'
    uris: 'http://deb.debian.org/debian'
    suites:
      - 'bookworm'
      - 'bookworm-updates'
      - 'bookworm-backports'
    components:
      - 'main'
      - 'contrib'
      - 'non-free'
      - 'non-free-firmware'
    signed_by: '/usr/share/keyrings/debian-archive-keyring.gpg'
  - name: 'debian-security'
    types:
      - 'deb'
      - 'deb-src'
    uris: 'http://deb.debian.org/debian-security'
    suites:
      - 'bookworm-security'
    components:
      - 'main'
      - 'contrib'
      - 'non-free'
      - 'non-free-firmware'
    signed_by: '/usr/share/keyrings/debian-archive-keyring.gpg'
