---
dependency:
  name: galaxy
driver:
  name: podman
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent  # suppress warnings
      callback_whitelist: profile_tasks, timer, yaml  # output profiling info
    ssh_connection:
      pipelining: false  # does not work with podman
platforms:
  - name: debian-12
    image: ghcr.io/hifis-net/debian-systemd:12
    systemd: always
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN  # required for systemd systems
    command: "/lib/systemd/systemd"
    pre_build_image: true
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
