---
###############################################################################
# FIKA Prep
###############################################################################
#
# Generates:
#   _fika_nvm_dir: str - absolute path to nvm repo.
#   _fika_spt_dir: str - absolute path to spt repo.
#   _fika_eft_dir: str - absolute path to eft install.

- name: 'Prep | assert version requirements'
  ansible.builtin.assert:
    quiet: true
    that:
      - fika_service_spt_version | length > 0
      - fika_service_server_version | length > 0
      - fika_service_node_version | length > 0
    fail_msg: |
      All service versions must be set.

        fika_service_spt_version
        fika_service_server_version
        fika_service_node_version

- name: 'Prep | parse options'
  ansible.builtin.set_fact:
    _fika_nvm_dir: '{{ fika_role_config_dir }}/.nvm'
    _fika_spt_dir: '{{ fika_role_config_dir }}/spt'
    _fika_eft_dir: '{{ fika_role_config_dir }}/eft'

- name: 'Prep | manage users'
  when: fika_create_user
  ansible.builtin.include_role:
    name: 'r_pufky.deb.users'
    tasks_from: 'role_account_add.yml'
  vars:
    users_role_group: '{{ fika_role_group }}'
    users_role_user: '{{ fika_role_user }}'

- name: 'Prep | set {{ fika_role_config_dir }}'
  ansible.builtin.file:
    path: '{{ _fika_eft_dir }}'
    owner: '{{ fika_user }}'
    group: '{{ fika_group }}'
    mode: '0755'
    state: 'directory'

